http_server:
  port: 8080
  use_custom_validator: true

mongodb:
  host: "mongodb://localhost"
  port: 27017

auth:
  expire_duration: "1440m"
  sign_key: "secret"

mysql:
  db_name: "newsapp_db"
  host: "localhost"
  port: 3308
  username: "newsapp"
  password: "newsappt0lk2o20"

zap_logger:
  file_path: "./logs/log.json"
  use_local_time: false
  file_max_size_in_mb: 10
  file_max_age_in_days: 30